### ISSUE TITLE
AzureDevOpsDsc: Enums should move out of prefix file

### ISSUE THREAD

**Issue by johlju** [dsccommunity/AzureDevOpsDsc#12]
Like 'Classes' enums should be single ps1 files with 1 enum definition per file. Compilation will put them in the main module psm1.
No needs for subfolders in enums. 

https://github.com/dsccommunity/AzureDevOpsDsc/blob/8d43d12989359b8facdf46d86011a34dfe787898/source/prefix.ps1#L13-L28

_As per https://github.com/dsccommunity/AzureDevOpsDsc/pull/7#issuecomment-729941083._

**Comment by SphenicPaul** [comment]
@johlju / @gaelcolas - Regarding this point, having moved the enums into their own directory (and files) and out of the `prefix.ps1`, the enums don't end up in the final `AzureDevOps.psm1` file. The classes that use/require them hit errors when the `.psm1` file is run/loaded because the enums aren't present.

See fork branch [here](https://github.com/SphenicPaul/AzureDevOpsDsc/tree/pjw-issue12-MoveEnumsFromPrefixFile/source/Enums).

I'm skipping this for now but any thoughts/comments/suggestions welcome.

**Comment by johlju** [comment]
Well, it seems the folder name should be the very non-intuitive `Enum` and not `Enums`. One would not expect that since the other folder is `Classes` and not `Class`.  😆  

I had to double-check in this repo as I know @gaelcolas made it work there: https://github.com/dsccommunity/JeaDsc/tree/master/source

I learned something new today. 🙂

**Comment by gaelcolas** [comment]
It's a Module Builder thing, but yeah I agree that it's not very intuitive

**Comment by SphenicPaul** [comment]
Thanks both. That resolved it. 😄 

Added to PR #28.
